### ISSUE TITLE
Workflow do nothing when I select search option

### ISSUE THREAD

**Issue by mihan007** [yannickglt/alfred-devdocs#10]
Trying to find yii2 doc for "findAll":
![2016-08-01 at 10 54](https://cloud.githubusercontent.com/assets/939122/17287147/9311d290-57d6-11e6-87b1-02c3a3f20014.png)
Nothing happens when I click "Enter" or "cmd+1" or "shift+cmd+1".
Expected: open browser window with documentation (or QuickLook window with shift)

But when I trying to search using the alias: "yii~2.0 findAll" it opens search result page at browser when I click cmd+1, cmd+2,.. Also it opens search result page at browser when I click shift+cmd+1, shift+cmd+2... But with shift it's expected to open search result at QuickLook window:
![2016-08-01 at 10 57](https://cloud.githubusercontent.com/assets/939122/17287264/4c5a4f20-57d7-11e6-938b-0df8a058c854.png)

**Comment by yannickglt** [comment]
Hi,
Thank your for using alfred-devdocs.
The issue should be fixed with v1.1.1.
