### ISSUE TITLE
doesn't work on Alfred v2.8.6 (411)

### ISSUE THREAD

**Issue by vyorkin** [yannickglt/alfred-devdocs#14]
Alfred says that I need to update to the pre-release version:
![image](https://cloud.githubusercontent.com/assets/988849/20245554/d2a0bd24-a9b4-11e6-8678-d1fbe1c9f498.png)

**Comment by yannickglt** [comment]
It should be fixed with the last version of the workflow and the version [2.8.8](https://www.alfredapp.com/help/v2/) of Alfred.
