### ISSUE TITLE
Support for React

### ISSUE THREAD

**Issue by Overload119** [yannickglt/alfred-devdocs#15]

**Comment by yannickglt** [comment]
As React is already supported by devdocs.io, it is also supported by alfred-devdocs. Do you have the last version of alfred-devdocs?

You can add the React documentation using the command `cdoc:add react`.
![image](https://cloud.githubusercontent.com/assets/1006426/22182351/c7fa8276-e0a3-11e6-9a58-f67902ed5c47.png)

Then, you can use it by typing `react ` and additional keywords.
![image](https://cloud.githubusercontent.com/assets/1006426/22182352/cacac56a-e0a3-11e6-99df-90d35901ae54.png)

**Comment by Overload119** [comment]
Thank you! I just had an older version.
