### ISSUE TITLE
Can you make this work behind a proxy?

### ISSUE THREAD

**Issue by marlun** [yannickglt/alfred-devdocs#18]
Is there some environment variables I can set to make this work behind a proxy? I've HTTP_PROXY and HTTPS_PROXY set but it doesn't help.

**Comment by yannickglt** [comment]
You should be able to do it now thanks to the Alfred environment variable `HTTP_PROXY`. See https://github.com/yannickglt/alfred-devdocs#use-behind-an-http-proxy to get further information.

**Comment by marlun** [comment]
It works, thanks!
