### ISSUE TITLE
Allow creating custom aliases of docs

### ISSUE THREAD

**Issue by yannickglt** [yannickglt/alfred-devdocs#19]
The ability to create tiny aliases would improve the ux.

For example, the keyword for the last Angular's doc is `angular~4_typescript` which is quiet long.
![image](https://cloud.githubusercontent.com/assets/1006426/25640794/5b70283a-2f91-11e7-9e6a-5a4871e25b45.png)

Thanks to this feature, we would be able to create a fast and simple alias `ng` to get access the same documentation.
![image](https://cloud.githubusercontent.com/assets/1006426/25640769/3c5d6cb4-2f91-11e7-9171-d76766d2d81a.png)

Obviously, this feature does make sense only if there is the ability to save and keep aliases after upgrades of the workflow. It should not be so much complicated by using the same system as local data and documentation caching.

**Comment by JReinhold** [comment]
would be awesome if this was implemented.

**Comment by yannickglt** [comment]
Resolved by ad42cf21e05a29c0304eaedabd2227cc2b45c383
