### ISSUE TITLE
cdoc commands

### ISSUE THREAD

**Issue by BlackSheepWithMe** [yannickglt/alfred-devdocs#2]
Love the workflow, it will help a ton. Though I am unclear on how to use the cdoc:* commands. Where do I use them?

**EDIT:** Looks like v.1.0.0 doesn't have conf files. (Thats what your curl is grabbing)

**Comment by yannickglt** [comment]
Thank you and you are right. Readme was updated with version 1.0.1.

**Comment by pn320** [comment]
I'm sorry, I'm still unclear on where to use the `cdoc` command. Whenever I use it in iterm with a fish shell, it simply gives me this error
`fish: Unknown command: cdoc:add`
