### ISSUE TITLE
how does this thing work?

### ISSUE THREAD

**Issue by sw-yx** [yannickglt/alfred-devdocs#23]
Hello ssorry for the nooby question but this thing doesnt seem to be working for me.. i installed it as normal but I am not sure what to type to activate it...

its definitely installed...
![image](https://user-images.githubusercontent.com/6764957/31848054-2215de62-b5f7-11e7-8c3e-efd4ca31a4e6.png)

but i am unable to search anything...
![image](https://user-images.githubusercontent.com/6764957/31848052-1161cfb8-b5f7-11e7-8a95-8a536a18358d.png)

**Comment by yannickglt** [comment]
Hi. 
Thanks for installing the workflow.
First, you must to install docs using the command `cdoc:add react`. Then you should be able to look for a React doc part using `react anything` or `doc anything`. Don't forget, you can use the TAB key to autocomplete your search and the SHIFT key to get a preview of the doc.
Enjoy!

**Comment by sw-yx** [comment]
ah, wonderful! might want to tweak the readme to say that. thank you very much.
