### ISSUE TITLE
Search results fewer than on DevDocs

### ISSUE THREAD

**Issue by brandenbyers** [yannickglt/alfred-devdocs#3]
Search results are not consistent with DevDocs. For example, when searching Javascript for "acceleration" on DevDocs.io returns results for `DeviceMotionEvent` and others.

![image](https://cloud.githubusercontent.com/assets/7098232/8133983/5264db52-10f1-11e5-93bc-0b78e6499532.png)

When using the same query string in this Alfred workflow, the results return nothing. The closest it comes is "acce" returns "Property Accessors (Operators)," but then no more results as I continue to type.

What differs with your method of search?

**Comment by yannickglt** [comment]
I think you must search using the keyword "dom" instead of "javascript" to get the expected results.
