### ISSUE TITLE
cdoc:refresh All docs errors

### ISSUE THREAD

**Issue by brandenbyers** [yannickglt/alfred-devdocs#4]
Refreshing docs individually works as expected, but `cdoc:refresh` "All docs" returns an error. I'm not familiar with where these messages get logged (attempted logging them through the workflow debugger, but there were no results).

All that I have is the snippet from the notification:

![image](https://cloud.githubusercontent.com/assets/7098232/8134163/a9388086-10f2-11e5-940d-3dd9da5e95d8.png)

I'd be happy to provide the full error message if you have a suggestion on where I can find it. Thanks.

**Comment by yannickglt** [comment]
Should be fixed with version 1.0.2.
