### ISSUE TITLE
Workflow disappears when adding all docs

### ISSUE THREAD

**Issue by teleject** [yannickglt/alfred-devdocs#7]
When using cdoc:add and request all docs to be added, the workflow disappears from Alfred app.

Reinstalling/replacing devdocs workflow brings it back, but have to install docs manually to keep it working.

**Comment by yannickglt** [comment]
It should be fixed with https://github.com/yannickglt/alfred-devdocs/commit/8d6d28e4de1cf07816c6012c6c3f41fe03701f51 and new packal version.

**Comment by teleject** [comment]
👍
